module.exports = {
  DestinyManifestDefinition: {
    DestinyNodeStepSummaryDefinition: "DestinyNodeStepSummaryDefinition",
    DestinyArtDyeChannelDefinition: "DestinyArtDyeChannelDefinition",
    DestinyArtDyeReferenceDefinition: "DestinyArtDyeReferenceDefinition",
    DestinyPlaceDefinition: "DestinyPlaceDefinition",
    DestinyActivityDefinition: "DestinyActivityDefinition",
    DestinyActivityTypeDefinition: "DestinyActivityTypeDefinition",
    DestinyClassDefinition: "DestinyClassDefinition",
    DestinyGenderDefinition: "DestinyGenderDefinition",
    DestinyInventoryBucketDefinition: "DestinyInventoryBucketDefinition",
    DestinyRaceDefinition: "DestinyRaceDefinition",
    DestinyTalentGridDefinition: "DestinyTalentGridDefinition",
    DestinyUnlockDefinition: "DestinyUnlockDefinition",
    DestinyMaterialRequirementSetDefinition:
      "DestinyMaterialRequirementSetDefinition",
    DestinySandboxPerkDefinition: "DestinySandboxPerkDefinition",
    DestinyStatGroupDefinition: "DestinyStatGroupDefinition",
    DestinyProgressionMappingDefinition: "DestinyProgressionMappingDefinition",
    DestinyFactionDefinition: "DestinyFactionDefinition",
    DestinyVendorGroupDefinition: "DestinyVendorGroupDefinition",
    DestinyRewardSourceDefinition: "DestinyRewardSourceDefinition",
    DestinyUnlockValueDefinition: "DestinyUnlockValueDefinition",
    DestinyRewardMappingDefinition: "DestinyRewardMappingDefinition",
    DestinyRewardSheetDefinition: "DestinyRewardSheetDefinition",
    DestinyItemCategoryDefinition: "DestinyItemCategoryDefinition",
    DestinyDamageTypeDefinition: "DestinyDamageTypeDefinition",
    DestinyActivityModeDefinition: "DestinyActivityModeDefinition",
    DestinyMedalTierDefinition: "DestinyMedalTierDefinition",
    DestinyAchievementDefinition: "DestinyAchievementDefinition",
    DestinyActivityGraphDefinition: "DestinyActivityGraphDefinition",
    DestinyActivityInteractableDefinition:
      "DestinyActivityInteractableDefinition",
    DestinyBondDefinition: "DestinyBondDefinition",
    DestinyCharacterCustomizationCategoryDefinition:
      "DestinyCharacterCustomizationCategoryDefinition",
    DestinyCharacterCustomizationOptionDefinition:
      "DestinyCharacterCustomizationOptionDefinition",
    DestinyCollectibleDefinition: "DestinyCollectibleDefinition",
    DestinyDestinationDefinition: "DestinyDestinationDefinition",
    DestinyEntitlementOfferDefinition: "DestinyEntitlementOfferDefinition",
    DestinyEquipmentSlotDefinition: "DestinyEquipmentSlotDefinition",
    DestinyStatDefinition: "DestinyStatDefinition",
    DestinyInventoryItemDefinition: "DestinyInventoryItemDefinition",
    DestinyInventoryItemLiteDefinition: "DestinyInventoryItemLiteDefinition",
    DestinyItemTierTypeDefinition: "DestinyItemTierTypeDefinition",
    DestinyLocationDefinition: "DestinyLocationDefinition",
    DestinyLoreDefinition: "DestinyLoreDefinition",
    DestinyMetricDefinition: "DestinyMetricDefinition",
    DestinyObjectiveDefinition: "DestinyObjectiveDefinition",
    DestinyPlatformBucketMappingDefinition:
      "DestinyPlatformBucketMappingDefinition",
    DestinyPlugSetDefinition: "DestinyPlugSetDefinition",
    DestinyPowerCapDefinition: "DestinyPowerCapDefinition",
    DestinyPresentationNodeDefinition: "DestinyPresentationNodeDefinition",
    DestinyProgressionDefinition: "DestinyProgressionDefinition",
    DestinyProgressionLevelRequirementDefinition:
      "DestinyProgressionLevelRequirementDefinition",
    DestinyRecordDefinition: "DestinyRecordDefinition",
    DestinyRewardAdjusterPointerDefinition:
      "DestinyRewardAdjusterPointerDefinition",
    DestinyRewardAdjusterProgressionMapDefinition:
      "DestinyRewardAdjusterProgressionMapDefinition",
    DestinyRewardItemListDefinition: "DestinyRewardItemListDefinition",
    DestinySackRewardItemListDefinition: "DestinySackRewardItemListDefinition",
    DestinySandboxPatternDefinition: "DestinySandboxPatternDefinition",
    DestinySeasonDefinition: "DestinySeasonDefinition",
    DestinySeasonPassDefinition: "DestinySeasonPassDefinition",
    DestinySocketCategoryDefinition: "DestinySocketCategoryDefinition",
    DestinySocketTypeDefinition: "DestinySocketTypeDefinition",
    DestinyTraitDefinition: "DestinyTraitDefinition",
    DestinyTraitCategoryDefinition: "DestinyTraitCategoryDefinition",
    DestinyUnlockCountMappingDefinition: "DestinyUnlockCountMappingDefinition",
    DestinyUnlockEventDefinition: "DestinyUnlockEventDefinition",
    DestinyUnlockExpressionMappingDefinition:
      "DestinyUnlockExpressionMappingDefinition",
    DestinyVendorDefinition: "DestinyVendorDefinition",
    DestinyMilestoneDefinition: "DestinyMilestoneDefinition",
    DestinyActivityModifierDefinition: "DestinyActivityModifierDefinition",
    DestinyReportReasonCategoryDefinition:
      "DestinyReportReasonCategoryDefinition",
    DestinyArtifactDefinition: "DestinyArtifactDefinition",
    DestinyBreakerTypeDefinition: "DestinyBreakerTypeDefinition",
    DestinyChecklistDefinition: "DestinyChecklistDefinition",
    DestinyEnergyTypeDefinition: "DestinyEnergyTypeDefinition",
  },
  DestinyComponentType: {
    Profiles: 100,
    VendorReceipts: 101,
    ProfileInventories: 102,
    ProfileCurrencies: 103,
    ProfileProgression: 104,
    PlatformSilver: 105,
    Characters: 200,
    CharacterInventories: 201,
    CharacterProgressions: 202,
    CharacterRenderData: 203,
    CharacterActivities: 204,
    CharacterEquipment: 205,
    ItemInstances: 300,
    ItemObjectives: 301,
    ItemPerks: 302,
    ItemRenderData: 303,
    ItemStats: 304,
    ItemSockets: 305,
    ItemTalentGrids: 306,
    ItemCommonData: 307,
    ItemPlugStates: 308,
    ItemPlugObjectives: 309,
    ItemReusablePlugs: 310,
    Vendors: 400,
    VendorCategories: 401,
    VendorSales: 402,
    Kiosks: 500,
    CurrencyLookups: 600,
    PresentationNodes: 700,
    Collectibles: 800,
    Records: 900,
    Transitory: 1000,
    Metrics: 1100,
    StringVariables: 1200,
  },
  DestinyClass: {
    Titan: 0,
    Hunter: 1,
    Warlock: 2,
    Unknown: 3,
  },
};
